<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>com.epau.app</groupId>
    <artifactId>flashcard-app-installer</artifactId>
    <version>1.0.1</version>

    <properties>
        <java.version>25</java.version>
        <flatlaf.version>3.7.2</flatlaf.version>
        <maven.compiler.source>${java.version}</maven.compiler.source>
        <maven.compiler.target>${java.version}</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <module.path>${project.build.directory}/modules</module.path>
        <module.name>com.epau.app.flashcard.app.installer</module.name>
        <main.class>com.epau.app.flashcard.app.installer.Main</main.class>
        <app.main>Flashcard App Installer</app.main>
    </properties>

    <dependencies>
        <dependency>
            <groupId>com.epau</groupId>
            <artifactId>installer</artifactId>
            <version>1.0.0</version>
        </dependency>
        <dependency>
            <groupId>com.epau.utilities.swing</groupId>
            <artifactId>swing-operation</artifactId>
            <version>1.0.0</version>
        </dependency>
        <dependency>
            <groupId>com.epau.utilities.stream</groupId>
            <artifactId>stream-utilities</artifactId>
            <version>1.0.0</version>
        </dependency>

        <dependency>
            <groupId>com.formdev</groupId>
            <artifactId>flatlaf</artifactId>
            <version>${flatlaf.version}</version>
        </dependency>
        <dependency>
            <groupId>org.apache.commons</groupId>
            <artifactId>commons-compress</artifactId>
            <version>1.28.0</version>
            <scope>compile</scope>
        </dependency>
        <dependency>
            <groupId>com.formdev</groupId>
            <artifactId>flatlaf-extras</artifactId>
            <version>${flatlaf.version}</version>
        </dependency>
        <dependency>
            <groupId>org.jetbrains.pty4j</groupId>
            <artifactId>pty4j</artifactId>
            <version>0.13.12</version>
        </dependency>
        <dependency>
            <groupId>org.postgresql</groupId>
            <artifactId>postgresql</artifactId>
            <version>42.7.13</version>
            <scope>compile</scope> <!-- explicit -->
        </dependency>
        <dependency>
            <groupId>org.checkerframework</groupId>
            <artifactId>checker-qual</artifactId>
            <version>3.55.1</version>
            <scope>runtime</scope>
        </dependency>
        <dependency>
            <groupId>com.github.weisj</groupId>
            <artifactId>jsvg</artifactId>
            <version>2.1.0</version>
        </dependency>
        <dependency>
            <groupId>org.jetbrains</groupId>
            <artifactId>annotations</artifactId>
            <version>24.0.1</version>
        </dependency>

        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter</artifactId>
            <version>6.1.3</version>
            <scope>test</scope>
        </dependency>
    </dependencies>

    <build>
        <pluginManagement>
            <plugins>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-jlink-plugin</artifactId>
                    <version>3.3.0</version>
                    <configuration>
                        <modulePaths>
                            <modulePath>${module.path}</modulePath>
                        </modulePaths>
                        <stripDebug>true</stripDebug>
                        <noHeaderFiles>true</noHeaderFiles>
                        <noManPages>true</noManPages>
                    </configuration>
                </plugin>
            </plugins>

        </pluginManagement>
        <plugins>

            <plugin>
                <groupId>org.moditect</groupId>
                <artifactId>moditect-maven-plugin</artifactId>
                <version>1.3.0.Final</version>
                <executions>
                    <execution>
                        <id>add-module-info-to-dependencies</id>
                        <phase>package</phase>
                        <goals>
                            <goal>add-module-info</goal>
                        </goals>
                        <configuration>
                            <overwriteExistingFiles>true</overwriteExistingFiles>
                            <jdepsExtraArgs>
                                <arg>--ignore-missing-deps</arg>
                                <arg>--multi-release</arg>
                                <arg>${java.version}</arg>
                            </jdepsExtraArgs>

                            <modules>
                                <module>
                                    <artifact>
                                        <groupId>net.java.dev.jna</groupId>
                                        <artifactId>jna</artifactId>
                                    </artifact>
                                    <moduleInfo>
                                        <name>com.sun.jna</name>
                                    </moduleInfo>
                                </module>
                                <module>
                                    <artifact>
                                        <groupId>net.java.dev.jna</groupId>
                                        <artifactId>jna-platform</artifactId>
                                    </artifact>
                                    <moduleInfo>
                                        <name>com.sun.jna.platform</name>
                                    </moduleInfo>
                                </module>
                                <module>
                                    <artifact>
                                        <groupId>org.postgresql</groupId>
                                        <artifactId>postgresql</artifactId>
                                    </artifact>
                                    <moduleInfo>
                                        <name>org.postgresql.jdbc</name>
                                    </moduleInfo>
                                </module>
                                <module>
                                    <artifact>
                                        <groupId>org.jetbrains.pty4j</groupId>
                                        <artifactId>pty4j</artifactId>
                                    </artifact>
                                    <moduleInfo>
                                        <name>pty4j</name>
                                    </moduleInfo>
                                </module>
                            </modules>
                        </configuration>
                    </execution>

                </executions>
            </plugin>

            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-jar-plugin</artifactId>
                <version>3.5.1</version>
                <configuration>
                    <outputDirectory>${module.path}</outputDirectory>
                </configuration>
            </plugin>

            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-dependency-plugin</artifactId>
                <executions>
                    <execution>
                        <id>copy-dependencies</id>
                        <phase>process-resources</phase>
                        <goals>
                            <goal>copy-dependencies</goal>
                        </goals>
                        <configuration>
                            <includeScope>runtime</includeScope>
                            <outputDirectory>${module.path}</outputDirectory>
                        </configuration>
                    </execution>
                </executions>
            </plugin>

            <plugin>
                <groupId>org.panteleyev</groupId>
                <artifactId>jpackage-maven-plugin</artifactId>
                <version>1.8.0</version>
                <executions>
                    <execution>
                        <id>jpackage</id>
                        <phase>package</phase>
                        <goals>
                            <goal>jpackage</goal>
                        </goals>
                    </execution>
                </executions>
                <configuration>
                    <name>${app.main}</name>
                    <appVersion>${project.version}</appVersion>
                    <icon>src/main/resources/icons/installer-app-logo.png</icon>
                    <linuxShortcut>true</linuxShortcut>
                    <modulePaths>
                        <path>${module.path}</path>
                    </modulePaths>
                    <module>${module.name}/${main.class}</module>
                    <destination>${project.build.directory}/jpackage</destination>
                </configuration>
            </plugin>
        </plugins>
    </build>
</project>