package com.fes.flashcard.installer;

import com.fes.flashcard.installer.page.Page;

import javax.swing.JComponent;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JSeparator;
import java.awt.*;


public class PageFrame extends JFrame {

	private JPanel        content;
	private PageTitleList pageTitleList;
	private JPanel        pageContent;
	private ButtonBar     buttonBar;
	private JLabel        pageDescription;
	// TODO is this necessary?
	private JScrollPane   pageTitleListScrollPane;

	public PageFrame() {
		$$$setupUI$$$();
		setTitle("Page Frame");
		setContentPane(content);
		setDefaultCloseOperation(EXIT_ON_CLOSE);
		setLocationRelativeTo(null);
		setSize(700, 500);
		setVisible(true);
	}

	private void createUIComponents() {
	}

	void showPage(Page page) {
		pageDescription.setText(page.getDescription());
		pageContent.removeAll();
		pageContent.add(page.getContent());
		pageContent.revalidate();
		pageContent.repaint();
	}

	public PageTitleList getPageTitleList() {
		return pageTitleList;
	}

	public ButtonBar getButtonsBar() {
		return buttonBar;
	}

	/**
	 * Method generated by IntelliJ IDEA GUI Designer
	 * >>> IMPORTANT!! <<<
	 * DO NOT edit this method OR call it in your code!
	 *
	 * @noinspection ALL
	 */
	private void $$$setupUI$$$() {
		content = new JPanel();
		content.setLayout(new GridBagLayout());
		pageTitleListScrollPane = new JScrollPane();
		GridBagConstraints gbc;
		gbc = new GridBagConstraints();
		gbc.gridx = 0;
		gbc.gridy = 0;
		gbc.gridheight = 4;
		gbc.weightx = 0.1;
		gbc.weighty = 1.0;
		gbc.fill = GridBagConstraints.BOTH;
		gbc.ipadx = 5;
		gbc.ipady = 5;
		content.add(pageTitleListScrollPane, gbc);
		pageTitleList = new PageTitleList();
		pageTitleList.setValueIsAdjusting(false);
		pageTitleListScrollPane.setViewportView(pageTitleList);
		pageDescription = new JLabel();
		pageDescription.setText("<Description>");
		gbc = new GridBagConstraints();
		gbc.gridx = 1;
		gbc.gridy = 0;
		gbc.weightx = 1.0;
		gbc.anchor = GridBagConstraints.WEST;
		gbc.insets = new Insets(10, 10, 10, 10);
		content.add(pageDescription, gbc);
		final JSeparator separator1 = new JSeparator();
		gbc = new GridBagConstraints();
		gbc.gridx = 1;
		gbc.gridy = 1;
		gbc.fill = GridBagConstraints.BOTH;
		content.add(separator1, gbc);
		pageContent = new JPanel();
		pageContent.setLayout(new BorderLayout(0, 0));
		gbc = new GridBagConstraints();
		gbc.gridx = 1;
		gbc.gridy = 2;
		gbc.weightx = 1.0;
		gbc.weighty = 1.0;
		gbc.fill = GridBagConstraints.BOTH;
		content.add(pageContent, gbc);
		buttonBar = new ButtonBar();
		gbc = new GridBagConstraints();
		gbc.gridx = 0;
		gbc.gridy = 4;
		gbc.gridwidth = 2;
		gbc.weightx = 1.0;
		gbc.fill = GridBagConstraints.HORIZONTAL;
		gbc.insets = new Insets(10, 10, 10, 10);
		content.add(buttonBar, gbc);
		final JSeparator separator2 = new JSeparator();
		gbc = new GridBagConstraints();
		gbc.gridx = 0;
		gbc.gridy = 3;
		gbc.gridwidth = 2;
		gbc.fill = GridBagConstraints.BOTH;
		content.add(separator2, gbc);
	}

	/**
	 * @noinspection ALL
	 */
	public JComponent $$$getRootComponent$$$() { return content; }

}
